apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logstash2
  labels:
    name: logstash2
  namespace: elk
spec:
  replicas: 1
  template:
    metadata:
      labels:
        elk: logstash2
    spec:
      containers:
      - name: logstash2
#        resources:
#          limits:
#            cpu: 400m
#            memory: 500Mi
#          requests:
#            cpu: 200m
#            memory: 256Mi
        env:
        - name: JAVA_HOME
          value: "/jdk1.8.0_101"
        - name: LOGSTASH
          value: "/logstash-2.4.1/bin/logstash"
        - name: PARAMETER1
          value: "-f"
        - name: PARAMETER2
          value: "/logstash-2.4.1/sendout.conf"
        image: reg.shenmintech.cn/logstash2.4:v1.1
        command: ["$(LOGSTASH)"]
        args: ["$(PARAMETER1)", "$(PARAMETER2)"]
        volumeMounts:
        - name: java
          mountPath: /jdk1.8.0_101
          readOnly: true
      imagePullSecrets:
      - name: regsecret
      volumes:
      - name: java
        hostPath:
          path: /opt/jdk1.8.0_101


