apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: registry
    spec:
      nodeName: uat2
      containers:
      - name: registry
        resources:
          limits:
            cpu: 2
            memory: 400Mi
          requests:
            cpu: 0.5
            memory: 200Mi
        image: registry:2
        ports:
        - containerPort: 5000
#          hostPort: 5000
          protocol: TCP
          name: registry-port
        volumeMounts:
        - name: registry
          mountPath: /var/lib/registry
          readOnly: false
        - name: registry-config
          mountPath: /etc/docker/registry
          readOnly: true
      - name: registry-web
        resources:
          limits:
            cpu: 2
            memory: 1400Mi
          requests:
            cpu: 0.5
            memory: 100Mi
        image: hyper/docker-registry-web
        ports:
        - containerPort: 8080
          protocol: TCP
          name: rgs-web-port
        volumeMounts:
        - name: registry-web-config
          mountPath: /conf
          readOnly: true
      volumes:
      - name: registry
        hostPath:
          path: /data/registry
      - name: registry-config
        hostPath:
          path: /data/docker_config/registry/
      - name: registry-web-config
        hostPath:
          path: /data/docker_config/registry-web/

---
apiVersion: v1
kind: Service
metadata:
  name: registry-web-svc
  labels:
    run: registry-web-svc
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    run: registry
  clusterIP: 172.18.155.4
