apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
#  namespace: kube-system
  labels:
    name: nginx
    version: 1.0
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: nginx
        version: 1.0
    spec:
      containers:
      - name: nginx
        image: reg.shenmintech.cn/nginx:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
#  namespace: kube-system
  labels:
    run: nginx-svc
spec:
  selector:
    run: nginx
  ports:
  - port: 80
    targetPort: 80
#    nodePort: 30280
  type: NodePort
