apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: authority
  labels:
    name: authority
  namespace: springcloud-test
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        run: authority
    spec:
      containers:
      - name: authority
        resources:
          limits:
            cpu: 600m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 256Mi
        env:
        - name: JAVA
          value: "/data/sprintcloud_sm/jdk1.8.0_101/bin/java"
        - name: PARAMETER1
          value: "-Xms128m"
        - name: PARAMETER2
          value: "-Xmx256m"
        - name: PARAMETER3
          value: "-jar"
        - name: FILENAME
          value: "/data/springcloud/com.shenmintech.authority-0.0.1-SNAPSHOT.jar"
        - name: PARAMETER4
          value: "--spring.profiles.active=test1"
        image: test2.shenmin.com:5000/authority:5.0.3.01
        ports:
        - containerPort: 8000
#          hostPort: 8000
        command: ["$(JAVA)"]
        args: ["$(PARAMETER1)", "$(PARAMETER2)", "$(PARAMETER3)", "$(FILENAME)", "$(PARAMETER4)"]
        volumeMounts:
        - name: java
          mountPath: /data/sprintcloud_sm
#          readOnly: true
      volumes:
      - name: java
        hostPath:
          path: /data2/k8springcloud
---
apiVersion: v1
kind: Service
metadata:
  name: smt-authority
  labels:
    run: smt-authority
  namespace: springcloud-test
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30003
    protocol: TCP
  selector:
    run: authority
