apiVersion: v1
kind: Pod
metadata: 
    name: busybox
    namespace: springcloud-test
spec:
    containers:
      - image: radial/busyboxplus:curl
        command:
          - sleep
          - "3600"
        imagePullPolicy: IfNotPresent
        name: busybox
    restartPolicy: Always
