apiVersion: v1
kind: Service
metadata:
  name: smt-dynamic
  labels:
    run: smt-dynamic
  namespace: springcloud-test
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 30007
    protocol: TCP
  selector:
    run: dynamic
