apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: kc
  labels:
    name: kc
  namespace: springcloud-test
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        run: kc
    spec:
      containers:
      - name: kc
        resources:
          limits:
            cpu: 600m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 256Mi
        env:
        - name: JAVA
          value: "/data/sprintcloud_sm/jdk1.8.0_101/bin/java"
        - name: PARAMETER1
          value: "-Xms128m"
        - name: PARAMETER2
          value: "-Xmx256m"
        - name: PARAMETER3
          value: "-jar"
        - name: FILENAME
          value: "/data/springcloud/kc-template.jar"
        - name: PARAMETER4
          value: "--spring.profiles.active=test1"
        image: test2.shenmin.com:5000/kc:5.0.3.01
        ports:
        - containerPort: 7010
#          hostPort: 7010
        command: ["$(JAVA)"]
        args: ["$(PARAMETER1)", "$(PARAMETER2)", "$(PARAMETER3)", "$(FILENAME)", "$(PARAMETER4)"]
        volumeMounts:
        - name: java
          mountPath: /data/sprintcloud_sm
#          readOnly: true
      volumes:
      - name: java
        hostPath:
          path: /data2/k8springcloud
---
apiVersion: v1
kind: Service
metadata:
  name: smt-kc
  labels:
    run: smt-kc
  namespace: springcloud-test
spec:
  type: NodePort
  ports:
  - port: 7010
    targetPort: 7010
    nodePort: 30008
    protocol: TCP
  selector:
    run: kc
