apiVersion: v1
kind: ReplicationController
metadata:
  name: leiting-nginx-v2
  namespace: springcloud-test
  labels:
    smt-app: nginx-v2
    version: 1.10.3
spec:
  replicas: 1
  selector:
    smt-app: nginx-v2
  template:
    metadata:
      labels:
        smt-app: nginx-v2
        version: 1.10.3
    spec:
      containers:
      - name: nginx-v2
        image: test2.shenmin.com:5000/nginx:1.12.0
        ports:
        - containerPort: 80
