apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: kube-system
  labels:
    name: nginx
    version: 1.10.3
spec:
  replicas: 2
#  selector:
#    run: nginx
  template:
    metadata:
      labels:
        run: nginx
        version: 1.10.3
    spec:
      containers:
      - name: nginx
        image: test2.shenmin.com:5000/nginx:1.10.3
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-namespace
  namespace: kube-system
  labels:
    run: test-namespace
spec:
  selector:
    run: nginx
  ports:
  - port: 80
    targetPort: 80
#    nodePort: 30280
  type: NodePort
