apiVersion: v1
kind: Service
metadata:
  name: nginx-v1
  namespace: springcloud-test
  labels:
    smt-app: nginx-v1
spec:
  selector:
    smt-app: nginx-v1
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30280
  type: NodePort
