apiVersion: v1
kind: ReplicationController
metadata:
  name: leiting-nginx-v1
  namespace: springcloud-test
  labels:
    smt-app: nginx-v1
    version: 1.10.3
spec:
  replicas: 2
  selector:
    smt-app: nginx-v1
  template:
    metadata:
      labels:
        smt-app: nginx-v1
        version: 1.10.3
    spec:
      containers:
      - name: nginx-v1
        image: test2.shenmin.com:5000/nginx:1.10.3
        ports:
        - containerPort: 80
