apiVersion: v1
kind: Service
metadata:
  name: alpha-nginx
  namespace: names1
  labels:
    run: alpha-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    run: my-nginx
