apiVersion: v1  
kind: LimitRange 
metadata:
  name: mylimits 
  namespace: names1 
spec: 
  limits: 
  - max: 
      cpu: "300m" 
      memory: 20Mi 
    min: 
      cpu: 200m
      memory: 16Mi 
    maxLimitRequestRatio: 
      cpu: 5 
      memory: 3 
    type: Pod 

  - default:  
      cpu: 300m 
      memory: 20Mi 
    defaultRequest: 
      cpu: 50m 
      memory: 5Mi
    max:
      cpu: "400"
      memory: 50Mi
    min: 
      cpu: 40m
      memory: 16Mi
    maxLimitRequestRatio:
      cpu: 5
      memory: 2
    type: Container 
