apiVersion: v1
kind: LimitRange
metadata:
  name: mylimits
  namespace: names1
spec:
  limits:
  - max:
      cpu: "1"
      memory: 300Mi
    min:
      cpu: 200m
      memory: 16Mi
    maxLimitRequestRatio:
      cpu: 5
      memory: 600Mi
    type: Pod

  - default:
      cpu: 1000m
      memory: 100Mi
    defaultRequest:
      cpu: 500m
      memory: 250Mi
    max:
      cpu: "2"
      memory: 1Gi
    min:
      cpu: 200m
      memory: 16Mi
    maxLimitRequestRatio:
      cpu: 1
      memory: 300Mi
    type: Container
