apiVersion: v1
kind: LimitRange
metadata:
  name: mylimits
  namespace: names1
spec:
  limits:
  - max:
      cpu: "1"
      memory: 300Mi
    min:
      cpu: 200m
      memory: 16Mi
    maxLimitRequestRatio:
      cpu: 5
      memory: 3
    type: Pod

  - default:
      cpu: 1100m #如果创建pod的时候没有设置最大使用多大cpu，则设置这里设置的值，这里我们设置的1000m，也就是1个cpu的百分之百。
      memory: 200Mi
    defaultRequest:
      cpu: 500m
      memory: 100Mi
    max:
      cpu: "2"
      memory: 1Gi
    min:
      cpu: 200m
      memory: 16Mi
    maxLimitRequestRatio:
      cpu: 3
      memory: 2
    type: Container
