apiVersion: v1  
kind: LimitRange 
metadata:
  name: mylimits 
  namespace: names1 
spec: 
  limits: 
  - max: 
      cpu: "300m" 
      memory: 20Mi 
    min: 
      cpu: 200m
      memory: 16Mi 
    maxLimitRequestRatio: 
      cpu: 10 
      memory: 3 
    type: Pod 

  - default:  
      cpu: 300m 
      memory: 20Mi 
    defaultRequest: 
      cpu: 50m 
      memory: 8Mi
    max:
      cpu: "400m"
      memory: 50Mi
    min: 
      cpu: 40m
      memory: 6Mi
    maxLimitRequestRatio:
      cpu: 10
      memory: 2
    type: Container 
