apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-tomcat
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: my-tomcat
    spec:
      containers:
      - name: my-tomcat
        resources:
          limits:
            cpu: 600m
            memory: 300Mi
          requests:
            cpu: 200m
            memory: 100Mi
        image: test2.shenmin.com:5000/alvin-tomcat:1.0.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
#          hostPort: 80
          protocol: TCP
          name: tomcat-port
        volumeMounts:
        - name: java
          mountPath: /opt/java
          readOnly: true
      volumes:
      - name: java
        hostPath:
          path: /root/jdk1.8.0_101

---
apiVersion: v1
kind: Service
metadata:
  name: my-tomcat
  labels:
    run: my-tomcat
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30081
    protocol: TCP
  selector:
    run: my-tomcat
